CREATE TABLE SKI (
    SKI_ID NUMBER NOT NULL,  -- 스키장 아이디 (PK)
    UUID NUMBER NOT NULL,  -- 관리자 UUID (관리자 계정과 연결)
    NAME VARCHAR2(100)  NOT NULL,  -- 스키장 이름
    LOCATION VARCHAR2(200)  NOT NULL,  -- 위치
    WEBCAM_UR VARCHAR2(300)  NULL,      -- 웹캠 URL
    CONSTRAINT PK_SKI PRIMARY KEY (SKI_ID),
    CONSTRAINT UUID FOREIGN KEY (UUID) REFERENCES USERS (UUID) ON DELETE CASCADE
);

CREATE TABLE SKI_RESERVATION (
    SKI_RESERV_ID NUMBER NOT NULL,  -- 예약 아이디 (PK)
    SKI_ID NUMBER NOT NULL,  -- 스키장 아이디 (FK)
    UUID NUMBER NOT NULL,  -- 회원 UUID
    RESERV_DATE DATE NOT NULL,  -- 예약 날짜
    TOTAL_PRICE NUMBER(10,2) NULL,  -- 총 가격
    STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN ('CONFIRMED', 'CANCELLED', 'COMPLETED')), -- 예약 상태
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, -- 예약 생성일 (SYSDATE 사용)
    
    CONSTRAINT PK_SKI_RESERVATION PRIMARY KEY (SKI_RESERV_ID),
    CONSTRAINT FK_SKI_RESERVATION_SKI FOREIGN KEY (SKI_ID) REFERENCES SKI (SKI_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SKI_RESERVATION_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID) ON DELETE CASCADE
);

CREATE TABLE SKI_ITEM (
    ITEM_ID NUMBER NOT NULL,  -- 장비 아이디 (PK)
    CATEGORY_ID NUMBER NOT NULL,  -- 카테고리 아이디 (FK)
    SKI_ID NUMBER NOT NULL,  -- 스키장 아이디 (FK)
    ITEM_DETAIL VARCHAR2(100) NULL,      -- 장비 상세 정보
    TOTAL_QUANTITY NUMBER NOT NULL,  -- 총 장비 수량
    CREATED_AT DATE NOT NULL,  -- 등록일
    CONSTRAINT PK_SKI_ITEM PRIMARY KEY (ITEM_ID),
    CONSTRAINT FK_SKI_ITEM_SKI FOREIGN KEY (SKI_ID) REFERENCES SKI (SKI_ID)
);

CREATE TABLE SKI_PAYMENTS (
    PAYMENT_ID NUMBER NOT NULL,  -- 결제 아이디 (PK)
    SKI_RESERV_ID NUMBER NOT NULL,  -- 스키장 예약 아이디 (FK)
    UUID NUMBER NOT NULL,  -- 회원 UUID
    TOTAL_PRICE NUMBER(10,2) NOT NULL,  -- 결제 금액
    PAYMENT_METHOD VARCHAR2(20) NOT NULL CHECK (PAYMENT_METHOD IN ('CARD', 'KAKAOPAY', 'NAVERPAY')), -- 결제 방식
    STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN ('결제완료', '결제취소')), -- 결제 상태
    IMP_UID VARCHAR2(50),    -- 포트원고유아이디
    CARD_NUM VARCHAR2(50),      -- 카드번호
    CARD_NAME VARCHAR2(25),      -- 카드사(이름)
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL , -- 결제 날짜
    
    CONSTRAINT PK_SKI_PAYMENTS PRIMARY KEY (PAYMENT_ID), 
    CONSTRAINT FK_SKI_PAYMENTS_RESERV FOREIGN KEY (SKI_RESERV_ID) REFERENCES SKI_RESERVATION (SKI_RESERV_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SKI_PAYMENTS_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID) ON DELETE CASCADE
);


--COMMENT 를 REVIEW_COMMENT로 변경
CREATE TABLE SKI_REVIEWS (
    REVIEW_ID      NUMBER         NOT NULL,  -- 리뷰 아이디 (PK)
    PAYMENT_ID     NUMBER         NOT NULL,  -- 결제 아이디 (FK)
    UUID           NUMBER         NOT NULL,  -- 회원 UUID
    SKI_ID         NUMBER         NOT NULL,  -- 스키장 아이디 (FK)
    RATING         NUMBER(3,1)    NOT NULL,  -- 리뷰 평점 (0~5점, 소수 1자리까지)
    REVIEW_COMMENT VARCHAR2(1000),           -- 리뷰 내용 (COMMENT → REVIEW_COMMENT로 변경)
    REVIEW_IMG     VARCHAR2(255),            -- 리뷰 이미지
    CREATED_AT     DATE DEFAULT SYSDATE,     -- 리뷰 작성일 (자동 입력)
    
    CONSTRAINT PK_SKI_REVIEWS PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FK_SKI_REVIEWS_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES SKI_PAYMENTS (PAYMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SKI_REVIEWS_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID) ON DELETE CASCADE,
    CONSTRAINT FK_SKI_REVIEWS_SKI FOREIGN KEY (SKI_ID) REFERENCES SKI (SKI_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_REVIEW_RATING CHECK (RATING BETWEEN 0 AND 5)
);