-- 장바구니 테이블
CREATE TABLE CART_ITEMS (
    CART_ID NUMBER PRIMARY KEY,
    UUID NUMBER NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL CHECK(CATEGORY IN ('SKI', 'RENTAL', 'RESORT')),
    REF_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    PRICE NUMBER(10,2) NOT NULL,
    CONSTRAINT FK_CART_UUID FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);

-- 찜 테이블
CREATE TABLE WISH (
    WISHLIST_ID NUMBER PRIMARY KEY,
    UUID NUMBER NOT NULL,
    CATEGORY VARCHAR2(50) NOT NULL CHECK(CATEGORY IN ('SKI', 'RENTAL', 'RESORT')),
    REF_ID NUMBER NOT NULL,
    CONSTRAINT FK_WISH_UUID FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);

-- 시퀀스
CREATE SEQUENCE CART_ITEMS_SEQ;
CREATE SEQUENCE WISH_SEQ;
