-- 렌탈샵 테이블
CREATE TABLE RENTALSHOP
(
    RENTALSHOP_ID NUMBER PRIMARY KEY,
    UUID          NUMBER               NOT NULL,
    NAME          VARCHAR2(200)        NOT NULL,
    LOCATION      VARCHAR2(200)        NOT NULL,
    REMAIN_IMG    VARCHAR2(255),
    RENTAL_PHONE VARCHAR2(255) NOT NULL,
    RESUB_IMG1    VARCHAR2(255),
    RESUB_IMG2    VARCHAR2(255),
    RESUB_IMG3    VARCHAR2(255),
    DESCRIPTION   VARCHAR2(1000),
    CREATED_AT    DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_RENTALSHOP_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);

insert into rentalshop values (1,1,'렌탈샵1','강원도','img1','010-1234-1234','img2','img3','img4','렌탈샵소개',sysdate);

-- 렌탈샵 예약 테이블
CREATE TABLE RENTAL_RESERVATION
(
    RENT_RESERV_ID NUMBER PRIMARY KEY,
    RENTALSHOP_ID  NUMBER                       NOT NULL,
    UUID           NUMBER                       NOT NULL,
    RENTAL_START   TIMESTAMP                    NOT NULL,
    RENTAL_END     TIMESTAMP                    NOT NULL,
    TOTAL_PRICE    NUMBER                       NOT NULL,
    STATUS         VARCHAR2(20) DEFAULT '예약완료' CHECK (STATUS IN ('예약완료', '대여중', '반납완료', '취소')),
    CREATED_AT     DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_RENTAL_RESERV_SHOP FOREIGN KEY (RENTALSHOP_ID) REFERENCES RENTALSHOP (RENTALSHOP_ID),
    CONSTRAINT FK_RENTAL_RESERV_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);


-- 렌탈샵 장비 카테고리
CREATE TABLE ITEM_CATEGORY
(
    CATEGORY_ID    NUMBER PRIMARY KEY,
    ITEM_TYPE      VARCHAR2(100) NOT NULL CHECK (ITEM_TYPE IN ('리프트권', '패키지', '스키', '보드', '보호구', '상의', '하의', '신발')),
    PRICE_PER_HOUR NUMBER
);


-- 렌탈샵 장비 유형 테이블
CREATE TABLE RENT_ITEM
(
    ITEM_ID        NUMBER PRIMARY KEY,
    CATEGORY_ID    NUMBER               NOT NULL,
    RENTALSHOP_ID  NUMBER               NOT NULL,
    ITEM_NAME    VARCHAR2(50)	    NOT NULL,
    ITEM_DETAIL    VARCHAR2(100),
    TOTAL_QUANTITY NUMBER               NOT NULL,
    ITEM_IMG    VARCHAR2(100) 	  NOT NULL,
    CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_RENT_ITEM_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES ITEM_CATEGORY (CATEGORY_ID),
    CONSTRAINT FK_RENT_ITEM_SHOP FOREIGN KEY (RENTALSHOP_ID) REFERENCES RENTALSHOP (RENTALSHOP_ID)
);

-- 렌탈 예약 상세 테이블
CREATE TABLE RENT_RESERVATION_ITEM
(
    RENT_ITEM_ID   NUMBER PRIMARY KEY,
    RENT_RESERV_ID NUMBER        NOT NULL,
    ITEM_ID        NUMBER        NOT NULL,
    QUANTITY       NUMBER        NOT NULL,
    SUBTOTAL_PRICE NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_RENTAL_RESERV FOREIGN KEY (RENT_RESERV_ID) REFERENCES RENTAL_RESERVATION (RENT_RESERV_ID),
    CONSTRAINT FK_RENTAL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES RENT_ITEM (ITEM_ID)
);

-- 렌탈샵 결제 테이블
CREATE TABLE RENT_PAYMENTS
(
    PAYMENT_ID     NUMBER PRIMARY KEY,
    RENT_RESERV_ID NUMBER               NOT NULL,
    UUID           NUMBER               NOT NULL,
    TOTAL_PRICE    NUMBER(10, 2)        NOT NULL,
    PAYMENT_METHOD VARCHAR2(50)         NOT NULL CHECK (PAYMENT_METHOD IN ('CARD', 'KAKAOPAY', 'NAVERPAY')),
    STATUS         VARCHAR2(20)         NOT NULL CHECK (STATUS IN ('완료', '환불', '결제중')),
    IMP_UID        VARCHAR2(50)         NOT NULL,
    CARD_NUM       VARCHAR2(50),
    CARD_NAME      VARCHAR2(50),
    CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_RENT_PAYMENTS_RESERV FOREIGN KEY (RENT_RESERV_ID) REFERENCES RENTAL_RESERVATION (RENT_RESERV_ID),
    CONSTRAINT FK_RENT_PAYMENTS_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);


-- 시퀀스
CREATE SEQUENCE RENTALSHOP_SEQ;
CREATE SEQUENCE RENTAL_RESERVATION_SEQ;
CREATE SEQUENCE RENT_RESERVATION_ITEM_SEQ;
CREATE SEQUENCE ITEM_CATEGORY_SEQ;
CREATE SEQUENCE RENT_ITEM_SEQ;
CREATE SEQUENCE RENT_PAYMENTS_SEQ;





