-- 리조트 테이블
CREATE TABLE RESORT (
	RESORT_ID NUMBER PRIMARY KEY,
	UUID NUMBER REFERENCES USERS(UUID) ON DELETE CASCADE,
	NAME VARCHAR2(200) NOT NULL,
	RESORT_TYPE VARCHAR2(15) CHECK(RESORT_TYPE IN('CONDO','HOSTEL')),
	RESORT_PHONE VARCHAR2(50) NOT NULL,
	LOCATION VARCHAR2(200) NOT NULL,
	REMAIN_IMG VARCHAR2(255) NOT NULL,
	RESUB_IMG1 VARCHAR2(255),
	RESUB_IMG2 VARCHAR2(255),
	RESUB_IMG3 VARCHAR2(255),
	DESCRIPTION VARCHAR2(1000), 
    CHECK_TIME  VARCHAR2(20),   
    CREATED_AT DATE DEFAULT SYSDATE 
);


-- 시퀀스
CREATE SEQUENCE RESORT_SEQ;

-- INSERT
INSERT INTO RESORT VALUES(RESORT_SEQ.NEXTVAL, 1, '홍길동', 'CONDO', '010-1111-1111', '강원도', 'IMG1', 'IMG2', 'IMG3', 'IMG4', '등록테스트1', '14시/10시', SYSDATE);
INSERT INTO RESORT VALUES(RESORT_SEQ.NEXTVAL, 2, '이길동', 'HOSTEL', '010-2222-2222', '경기도', 'IMG1', 'IMG2', 'IMG3', 'IMG4', '등록테스트2', '12시/11시', SYSDATE);

