-- 리조트 테이블
CREATE TABLE RESORT (
	RESORT_ID NUMBER PRIMARY KEY,
	UUID NUMBER REFERENCES USERS(UUID) ON DELETE CASCADE,
	NAME VARCHAR2(200) NOT NULL,
	RESORT_TYPE VARCHAR2(15) CHECK(RESORT_TYPE IN('CONDO','HOSTEL')),
	RESORT_PHONE VARCHAR2(50) NOT NULL,
	LOCATION VARCHAR2(200) NOT NULL,
	REMAIN_IMG VARCHAR2(255) NOT NULL,
	RESUB_IMG1 VARCHAR2(255),
	RESUB_IMG2 VARCHAR2(255),
	RESUB_IMG3 VARCHAR2(255),
	DESCRIPTION VARCHAR2(1000), 
    CHECK_TIME  VARCHAR2(20),   
    CREATED_AT DATE DEFAULT SYSDATE 
);

-- INSERT
INSERT INTO RESORT VALUES(RESORT_SEQ.NEXTVAL, 1, '홍길동', 'CONDO', '010-1111-1111', '강원도', 'IMG1', 'IMG2', 'IMG3', 'IMG4', '등록테스트1', '14시/10시', SYSDATE);
INSERT INTO RESORT VALUES(RESORT_SEQ.NEXTVAL, 2, '이길동', 'HOSTEL', '010-2222-2222', '경기도', 'IMG1', 'IMG2', 'IMG3', 'IMG4', '등록테스트2', '12시/11시', SYSDATE);
INSERT INTO RESORT VALUES(RESORT_SEQ.NEXTVAL, 3, '삼길동', 'HOSTEL', '010-3333-3333', '경기도', 'IMG1', 'IMG2', 'IMG3', 'IMG4', '등록테스트3', '12시/11시', SYSDATE);


-- 리조트 결제 테이블
CREATE TABLE PAYMENTS (
    payment_id   NUMBER PRIMARY KEY, 
    resort_reserv_id NUMBER REFERENCES ROOM_RESERVATION(resort_reserv_id) ON DELETE CASCADE,   
    uuid  NUMBER REFERENCES USERS(uuid) ON DELETE CASCADE, 
    total_price NUMBER(10,2) NOT NULL,  
    payment_method  VARCHAR2(20) CHECK(payment_method IN('CARD', 'KAKAOPAY', 'NAVERPAY')),
    status     VARCHAR2(20) DEFAULT '결제완료' CHECK(status IN('결제완료','결제취소')),  
    imp_uid    VARCHAR2(50) NOT NULL,   
    card_num   VARCHAR2(50),   
    card_name VARCHAR2(50),    
    created_at   DATE DEFAULT SYSDATE 
);

-- INSERT
INSERT INTO PAYMENTS VALUES(1,1,1,100000,'CARD','결제완료','IMP_UID1','CARDNUMBER1','신한카드',SYSDATE);
INSERT INTO PAYMENTS VALUES(2,2,2,150000,'KAKAOPAY','결제완료','IMP_UID2','CARDNUMBER2','카카오페이',SYSDATE);
INSERT INTO PAYMENTS VALUES(3,3,3,120000,'NAVERPAY','결제완료','IMP_UID3','CARDNUMBER3','네이버페이',SYSDATE);


-- 시퀀스
CREATE SEQUENCE RESORT_SEQ;
CREATE SEQUENCE PAYMENT_ID_SEQ;

