-- 리조트 리뷰 테이블
CREATE TABLE RESORT_REVIEWS(
    review_id  NUMBER PRIMARY KEY,  -- 리뷰 아이디
    -- payment_id  NUMBER REFERENCES PAYMENTS(payment_id) ON DELETE CASCADE, -- 결제 아이디  (
    payment_id NUMBER, -- 결제 테이블 생성전 임의의 값
    uuid  NUMBER REFERENCES USERS(uuid) ON DELETE CASCADE, -- 유저 아이디
    resort_id NUMBER NOT NULL, -- 리조트 아이디 
    rating NUMBER(3,2) NOT NULL CHECK(rating BETWEEN 1 AND 5), -- 별점
    resort_comment NOT NULL VARCHAR2(1000), -- 리뷰 내용
    review_img VARCHAR2(255),   -- 리뷰 이미지
    created_at DATE DEFAULT SYSDATE  -- 작성일
);

-- 리조트 리뷰 답변 테이블
CREATE TABLE RESORT_REVIEWS_RE(
    review_re_id  NUMBER PRIMARY KEY, -- 리뷰 답변 아이디
    review_id NUMBER REFERENCES RESORT_REVIEWS(review_id) ON DELETE CASCADE,  -- 리뷰 아이디
    uuid NUMBER REFERENCES USERS(uuid) ON DELETE CASCADE, -- 관리자 아이디
    content VARCHAR2(300) NOT NULL, -- 답변 내용
    created_at DATE DEFAULT SYSDATE -- 답변일  
);

--시퀀스
create sequence resort_review_seq;
create sequence resort_review_re_seq;


-- 렌탈샵 리뷰
CREATE TABLE RENTALSHOP_REVIEWS
(
    REVIEW_ID  NUMBER PRIMARY KEY,
    PAYMENT_ID NUMBER               NOT NULL,
    UUID       NUMBER               NOT NULL,
    RATING     NUMBER(3, 2)         NOT NULL CHECK (RATING BETWEEN 0 AND 5),
    RENTALSHOP_ID NUMBER NOT NULL,
    COMMENTS    VARCHAR2(1000)       NOT NULL,
    REVIEW_IMG VARCHAR2(255),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES RENT_PAYMENTS (PAYMENT_ID),
    CONSTRAINT FK_UUID FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);

-- INSERT
INSERT INTO RENTALSHOP_REVIEWS VALUES (1, 1, 1, 4, 1, '장비 상태가 좋고 친절했어요!', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (2, 2, 2, 3, 2, '시설은 괜찮았지만 직원이 좀 불친절했어요.', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (3, 3, 3, 5, 3, '최고의 경험이었어요! 강력 추천합니다.', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (4, 4, 4, 2, 4, '가격 대비 만족도가 낮았어요.', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (5, 5, 5, 1, 5, '가성비 좋고 편하게 이용했어요.', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (6, 1, 6, 4, 1, '장비 상태가 좋고 친절했어요!', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (7, 2, 7, 3, 2, '시설은 괜찮았지만 직원이 좀 불친절했어요.', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (8, 3, 8, 5, 3, '최고의 경험이었어요! 강력 추천합니다.', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (9, 4, 9, 2, 4, '가격 대비 만족도가 낮았어요.', NULL, SYSDATE);
INSERT INTO RENTALSHOP_REVIEWS VALUES (10, 5, 10, 1, 5, '가성비 좋고 편하게 이용했어요.', NULL, SYSDATE);

-- 시퀀스
CREATE SEQUENCE RENTALSHOP_REVIEWS_SEQ;

-- 스키장 리뷰
CREATE TABLE SKI_REVIEWS
(
    REVIEW_ID  NUMBER PRIMARY KEY,
    PAYMENT_ID NUMBER               NOT NULL,
    UUID       NUMBER               NOT NULL,
    RATING     NUMBER(3, 2)         NOT NULL CHECK (RATING BETWEEN 0 AND 5),
    SKI_ID NUMBER NOT NULL,
    COMMENTS   VARCHAR2(1000)       NOT NULL,
    REVIEW_IMG VARCHAR2(255),
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_SKI_PAYMENTS FOREIGN KEY (PAYMENT_ID) REFERENCES SKI_PAYMENTS (PAYMENT_ID),
    CONSTRAINT FK_SKI_UUID FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);

-- INSERT
INSERT INTO SKI_REVIEWS VALUES (1, 1, 1, 3, 1, '3점 드립니다.', NULL, SYSDATE);
INSERT INTO SKI_REVIEWS VALUES (2, 2, 2, 5, 2, '5점 드립니다.', NULL, SYSDATE);
INSERT INTO SKI_REVIEWS VALUES (3, 3, 3, 1, 3, '1점 드립니다.', NULL, SYSDATE);

-- 시퀀스
CREATE SEQUENCE SKI_REVIEWS_SEQ;
