-- 스키장 정보 테이블
CREATE TABLE SKI
(
    SKI_ID     NUMBER PRIMARY KEY,
    UUID       NUMBER        NOT NULL,
    NAME       VARCHAR2(100) NOT NULL,
    LOCATION   VARCHAR2(200) NOT NULL,
    WEBCAM_URL VARCHAR2(300),
    CONSTRAINT FK_SKI_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);
insert into ski values(1,1,'스키장1','강원도','url');
insert into ski values(2,2,'스키장2','경기도','url');
insert into ski values(3,3,'스키장3','전라도','url');

-- 스키장 예약 테이블
CREATE TABLE SKI_RESERVATION
(
    SKI_RESERV_ID NUMBER PRIMARY KEY,
    SKI_ID        NUMBER                       NOT NULL,
    UUID          NUMBER                       NOT NULL,
    RESERV_DATE   DATE                         NOT NULL,
    TOTAL_PRICE   NUMBER(10, 2),
    STATUS        VARCHAR2(20) DEFAULT '예약완료' CHECK (STATUS IN ('예약완료', '대여중', '반납완료', '취소')),
    CREATED_AT    DATE         DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_SKI_RESERV_SHOP FOREIGN KEY (SKI_ID) REFERENCES SKI (SKI_ID),
    CONSTRAINT FK_SKI_RESERV_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);

--INSERT
INSERT INTO SKI_RESERVATION VALUES (1, 1, 1, '25/04/01', 50000, '예약완료', SYSDATE);
INSERT INTO SKI_RESERVATION VALUES (2, 2, 2, '25/04/11', 70000, '예약완료', SYSDATE);
INSERT INTO SKI_RESERVATION VALUES (3, 3, 3, '25/04/07', 100000, '예약완료', SYSDATE);


-- 스키장 장비 유형 테이블
CREATE TABLE SKI_ITEM
(
    ITEM_ID        NUMBER PRIMARY KEY,
    CATEGORY_ID    NUMBER               NOT NULL,
    SKI_ID         NUMBER               NOT NULL,
    ITEM_NAME      VARCHAR2(50)         NOT NULL,
    ITEM_DETAIL    VARCHAR2(100),
    TOTAL_QUANTITY NUMBER               NOT NULL,
    ITEM_IMG       VARCHAR2(100)        NOT NULL,
    CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_SKI_ITEM_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES ITEM_CATEGORY (CATEGORY_ID),
    CONSTRAINT FK_SKI_ITEM_SHOP FOREIGN KEY (SKI_ID) REFERENCES SKI (SKI_ID)
);

-- 스키장 예약 항목 테이블
CREATE TABLE SKI_RESERVATION_ITEM
(
    SKI_ITEM_ID    NUMBER PRIMARY KEY,
    SKI_RESERV_ID  NUMBER        NOT NULL,
    ITEM_ID        NUMBER        NOT NULL,
    QUANTITY       NUMBER        NOT NULL,
    SUBTOTAL_PRICE NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_SKI_RESERV FOREIGN KEY (SKI_RESERV_ID) REFERENCES SKI_RESERVATION (SKI_RESERV_ID),
    CONSTRAINT FK_SKI_ITEM FOREIGN KEY (ITEM_ID) REFERENCES SKI_ITEM (ITEM_ID)
);

-- 스키장 결제 테이블
CREATE TABLE SKI_PAYMENTS
(
    PAYMENT_ID     NUMBER PRIMARY KEY,
    SKI_RESERV_ID  NUMBER               NOT NULL,
    UUID           NUMBER               NOT NULL,
    TOTAL_PRICE    NUMBER(10, 2)        NOT NULL,
    PAYMENT_METHOD VARCHAR2(50)         NOT NULL CHECK (PAYMENT_METHOD IN ('CARD', 'KAKAOPAY', 'NAVERPAY')),
    STATUS         VARCHAR2(20)         NOT NULL CHECK (STATUS IN ('완료', '환불', '결제중')),
    IMP_UID        VARCHAR2(50)         NOT NULL,
    CARD_NUM       VARCHAR2(50),
    CARD_NAME      VARCHAR2(50),
    CREATED_AT     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_SKI_PAYMENTS_RESERV FOREIGN KEY (SKI_RESERV_ID) REFERENCES SKI_RESERVATION (SKI_RESERV_ID),
    CONSTRAINT FK_SKI_PAYMENTS_USER FOREIGN KEY (UUID) REFERENCES USERS (UUID)
);

INSERT INTO SKI_PAYMENTS VALUES(1,1,1,100000,'CARD','완료','IMP_UID1','CARD_NUM1','신한카드',SYSDATE);
INSERT INTO SKI_PAYMENTS VALUES(2,2,2,70000,'CARD','완료','IMP_UID1','CARD_NUM2','KAKAOPAY',SYSDATE);
INSERT INTO SKI_PAYMENTS VALUES(3,3,3,900000,'CARD','완료','IMP_UID1','CARD_NUM3','NAVERPAY',SYSDATE);


-- 시퀀스
CREATE SEQUENCE SKI_REVIEWS_SEQ;
CREATE SEQUENCE SKI_PAYMENTS_SEQ;
CREATE SEQUENCE SKI_RESERVATION_ITEM_SEQ;
CREATE SEQUENCE SKI_ITEM_SEQ;
CREATE SEQUENCE SKI_SEQ;
CREATE SEQUENCE SKI_REVERVATION_SEQ