-- 유저 테이블

CREATE TABLE USERS (
	UUID NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(255) NOT NULL,
	NAME VARVHAR2(50) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	PHONE VARCHAR2(20),
	SOCIAL VARCHAR2(15) CHECK (SOCIAL IN ('NORMAL', 'KAKAO')),
	ROLE VARCHAR2(10) CHECK (ROLE IN ('USER', 'SKI', 'RENTAL', 'RESORT', 'ADMIN')),
	STATUS VARCHAR2(2) CHECK (STATUS IN ('P', 'Y', 'N')),
	CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

-- 유저 접속 기록
CREATE TABLE USER_LOG(
	IP VARCHAR2(40) PRIMARY KEY,
	CREATED_AT TIMESTAMP NOT NULL,
	CONSTRAINT USER_LOG_PK PRIMARY KEY(IP, CREATED_AT)
);

-- 일일 접속자 수를 저장하는 테이블
CREATE TABLE USER_LOG_COUNT(
    LOG_DATE DATE NOT NULL,
    LOG_COUNT NUMBER NOT NULL,
    UNIQUE_LOG_COUNT NUMBER NOT NULL
);

-- 시퀀스
CREATE SEQUENCE USERS_SEQ;

