-- 유저 테이블

CREATE TABLE USERS (
	UUID NUMBER PRIMARY KEY,
	USER_ID VARCHAR2(50) NOT NULL,
	PASSWORD VARCHAR2(255) NOT NULL,
	NAME VARVHAR2(50) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	PHONE VARCHAR2(20),
	SOCIAL VARCHAR2(15) CHECK (SOCIAL IN ('NORMAL', 'KAKAO')),
	ROLE VARCHAR2(10) CHECK (ROLE IN ('USER', 'SKI', 'RENTAL', 'RESORT', 'ADMIN')),
	STATUS VARCHAR2(2) CHECK (STATUS IN ('P', 'Y', 'N')),
	CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

-- 시퀀스
CREATE SEQUENCE USERS_SEQ;

