DROP TABLE USERS;
DROP SEQUENCE USERS_SEQ;

CREATE TABLE USERS
(
    UUID NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(50) NOT NULL,
    SOCIAL VARCHAR2(15) CHECK(SOCIAL IN('NORMAL', 'KAKAO')) NOT NULL,
    ROLE VARCHAR2(10) CHECK(ROLE IN('USER', 'SKI', 'RENTAL', 'RESORT', 'ADMIN')) NOT NULL,
    STATUS VARCHAR2(2) CHECK(STATUS IN('P', 'Y', 'N')) NOT NULL,
    REGDATE DATE NOT NULL
);

CREATE SEQUENCE USERS_SEQ;