-- 참고용

CREATE TABLE SKI_REVIEWS(

); -- 채우기

CREATE TABLE RENTALSHOP_REVIEWS(

); -- 채우기

CREATE TABLE RESORT_REVIEWS(

); -- 채우기

DROP TABLE SKI_REVIEW_RE;
DROP TABLE RENTALSHOP_REVIEW_RE;
DROP TABLE RESORT_REVIEW_RE;

CREATE TABLE SKI_REVIEW_RE(
	REVIEW_RE_ID NUMBER PRIMARY KEY,
	REVIEW_ID NUMBER REFERENCES SKI_REVIEWS(REVIEW_ID) NOT NULL,
	UUID NUMBER REFERENCES USERS(UUID) NOT NULL,
	CONTENT VARCHAR2(300) NOT NULL,
	CREATED_AT DATE NOT NULL
);

CREATE TABLE RENTALSHOP_REVIEW_RE(
	REVIEW_RE_ID NUMBER PRIMARY KEY,
	REVIEW_ID NUMBER REFERENCES RENTALSHOP_REVIEWS(REVIEW_ID) NOT NULL,
	UUID NUMBER REFERENCES USERS(UUID) NOT NULL,
	CONTENT VARCHAR2(300) NOT NULL,
	CREATED_AT DATE NOT NULL
);

CREATE TABLE RESORT_REVIEW_RE(
	REVIEW_RE_ID NUMBER PRIMARY KEY,
	REVIEW_ID NUMBER REFERENCES RESORT_REVIEWS(REVIEW_ID) NOT NULL,
	UUID NUMBER REFERENCES USERS(UUID) NOT NULL,
	CONTENT VARCHAR2(300) NOT NULL,
	CREATED_AT DATE NOT NULL
);

CREATE OR REPLACE VIEW REVIEWS_VIEW AS
SELECT 'SKI' AS CATEGORY, SR.REVIEW_ID, PAYMENT_ID, SR.UUID, SKI_ID AS REF_ID, (SELECT NAME FROM SKI WHERE SKI_ID = SR.SKI_ID) AS REF_NAME, RATING, REVIEW_COMMENT, IMG, SR.CREATED_AT,
    REVIEW_RE_ID, SRR.UUID R_UUID, CONTENT, SRR.CREATED_AT R_CREATED_AT
FROM SKI_REVIEWS SR LEFT JOIN SKI_REVIEW_RE SRR ON SR.REVIEW_ID = SRR.REVIEW_ID
UNION
SELECT 'RENTAL' AS CATEGORY, RR.REVIEW_ID, PAYMENT_ID, RR.UUID, RENTALSHOP_ID AS REF_ID, (SELECT NAME FROM RENTALSHOP WHERE RENTALSHOP_ID = RR.RENTALSHOP_ID) AS REF_NAME, RATING, REVIEW_COMMENT, IMG, RR.CREATED_AT,
    REVIEW_RE_ID, RRR.UUID R_UUID, CONTENT, RRR.CREATED_AT R_CREATED_AT
FROM RENTALSHOP_REVIEWS RR LEFT JOIN RENTALSHOP_REVIEW_RE RRR ON RR.REVIEW_ID = RRR.REVIEW_ID
UNION
SELECT 'RESORT' AS CATEGORY, RR.REVIEW_ID, PAYMENT_ID, RR.UUID, RESORT_ID AS REF_ID, (SELECT NAME FROM RESORT WHERE RESORT_ID = RR.RESORT_ID) AS REF_NAME, RATING, REVIEW_COMMENT, IMG, RR.CREATED_AT,
    REVIEW_RE_ID, RRR.UUID R_UUID, CONTENT, RRR.CREATED_AT R_CREATED_AT
FROM RESORT_REVIEWS RR LEFT JOIN RESORT_REVIEW_RE RRR ON RR.REVIEW_ID = RRR.REVIEW_ID;

INSERT INTO SKI_REVIEW_RE VALUES(1, 100, 21, '대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충', SYSDATE);
INSERT INTO SKI_REVIEW_RE VALUES(2, 101, 21, '대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충', SYSDATE);
INSERT INTO SKI_REVIEW_RE VALUES(3, 102, 21, '대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충 적당한답변대충', SYSDATE);

COMMIT;