-- 참고용

DROP TABLE RESORT_PAYMENTS;
DROP TABLE RESORT_RESERVATION;
DROP TABLE RESORT_ROOMS;
DROP TABLE RESORT;

CREATE TABLE RESORT(
	RESORT_ID NUMBER PRIMARY KEY,
    UUID NUMBER REFERENCES USERS(UUID) NOT NULL,
    NAME VARCHAR2(200) NOT NULL,
    RESORT_TYPE VARCHAR2(15) CHECK(RESORT_TYPE IN('콘도', '호텔')) NOT NULL,
    RESORT_PHONE VARCHAR2(50) NOT NULL,
    LOCATION VARCHAR2(200) NOT NULL,
    REMAIN_IMG VARCHAR2(255) NOT NULL,
    RESUB_IMG1 VARCHAR2(255),
    RESUB_IMG2 VARCHAR2(255),
    RESUB_IMG3 VARCHAR2(255),
    DESCRIPTION VARCHAR2(1000),
    CHECK_TIME VARCHAR2(20) NOT NULL,
    CREATED_AT DATE NOT NULL
);

CREATE TABLE RESORT_ROOMS(
    ROOM_ID NUMBER PRIMARY KEY,
    RESORT_ID NUMBER REFERENCES RESORT(RESORT_ID) NOT NULL,
    ROOM_NAME VARCHAR2(50) NOT NULL,
    ROOM_TYPE VARCHAR2(50) CHECK(ROOM_TYPE IN('SINGLE', 'TWIN', 'DOUBLE', 'SUITE', 'FAMILY')) NOT NULL,
    ROOM_QUANTITY NUMBER(3) NOT NULL,
    MAX_GUESTS NUMBER(2) NOT NULL,
    PRICE_PER_NIGHT NUMBER(10, 2) NOT NULL,
    RMAIN_IMG VARCHAR2(255) NOT NULL,
    RSUB_IMG1 VARCHAR2(255),
    RSUB_IMG2 VARCHAR2(255),
    RSUB_IMG3 VARCHAR2(255),
    DESCRIPTION VARCHAR2(1000),
    CREATED_AT DATE NOT NULL
);

CREATE TABLE RESORT_RESERVATION(
    RESORT_RESERV_ID NUMBER PRIMARY KEY,
    UUID NUMBER REFERENCES USERS(UUID) NOT NULL,
    ROOM_ID NUMBER REFERENCES RESORT_ROOMS(ROOM_ID) NOT NULL,
    CHECKIN_DATE DATE NOT NULL,
    CHECKOUT_DATE DATE NOT NULL,
    QUANTITY NUMBER(2) NOT NULL,
    TOTAL_PRICE NUMBER(10, 2) NOT NULL,
    STATUS VARCHAR2(20) CHECK(STATUS IN('예약', '취소', '완료')) NOT NULL,
    CREATED_AT DATE NOT NULL
);

CREATE TABLE RESORT_PAYMENTS(
    PAYMENT_ID NUMBER PRIMARY KEY,
    RESORT_RESERV_ID NUMBER REFERENCES RESORT_RESERVATION(RESORT_RESERV_ID) NOT NULL,
    UUID NUMBER REFERENCES USERS(UUID) NOT NULL,
    ROOM_ID NUMBER REFERENCES RESORT_ROOMS(ROOM_ID) NOT NULL,
    TOTAL_PRICE NUMBER(10, 2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(20) CHECK(PAYMENT_METHOD IN('CARD', 'KAKAOPAY', 'NAVERPAY')) NOT NULL,
    STATUS VARCHAR2(20) CHECK(STATUS IN('결제완료', '결제취소')) NOT NULL,
    IMP_UID VARCHAR2(50) NOT NULL,
    CARD_NUM VARCHAR2(50),
    CARD_NAME VARCHAR2(50),
    CREATED_AT DATE NOT NULL
);

SELECT * FROM RESORT;
SELECT * FROM RESORT_ROOMS;

INSERT INTO RESORT VALUES(1, 21, '곤지암 리조트', '콘도', '010-1111-1111', '위치', '메인', '서브', '서브', '서브', '설명', '시간', SYSDATE);
INSERT INTO RESORT_ROOMS VALUES(1, 1, '객실1', 'SINGLE', 10, 1, 50000, '메인', '서브', '서브', '서브', '설명', SYSDATE);
INSERT INTO RESORT_RESERVATION VALUES(1, 21, 1, SYSDATE, SYSDATE, 3, 150000, '예약', SYSDATE);
INSERT INTO RESORT_PAYMENTS VALUES(1, 1, 21, 1, 150000, 'KAKAOPAY', '결제완료', 'IMP', NULL, NULL, SYSDATE);

COMMIT;